/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HeaderDefault: typeof import('./src/components/Layout/HeaderDefault.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Popover: typeof import('./src/components/Base/Popover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarAuth: typeof import('./src/components/Layout/SidebarAuth.vue')['default']
    TabRight: typeof import('./src/components/Layout/TabRight.vue')['default']
  }
}
